services:

  php:
    image: php:8.2-fpm
    container_name: symfony_php
    working_dir: /var/www/symfony
    volumes:
      - .:/var/www/symfony
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - MESSENGER_TRANSPORT_DSN=amqp://guest:guest@rabbitmq:5672/%2f/messages
      - DATABASE_URL=postgresql://symfony_user:symfony_password@postgres:5432/symfony_db
    depends_on:
      - rabbitmq
      - database
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: >
      sh -c "apt-get update &&
             apt-get install -y librabbitmq-dev libssl-dev libpq-dev git unzip &&
             pecl install amqp &&
             docker-php-ext-enable amqp &&
             docker-php-ext-install pdo pdo_pgsql &&
             curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
             php-fpm"
    networks:
      - symfony_network

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - n8n
    networks:
      - symfony_network

  database:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - symfony_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - symfony_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - symfony_network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_TUNNEL_URL=https://<ngrok_url>/webhook  # Remplace <ngrok_url> par l'URL du tunnel si nécessaire
      - GENERIC_TIMEZONE=Europe/Paris
      - N8N_HOST=n8n
      - N8N_PROTOCOL=http
    networks:
      - symfony_network

volumes:
  postgres_data:
  redis_data:

networks:
  symfony_network:
    driver: bridge
